"""Self-contained HTML template for the Vantage knowledge graph.

Placeholders replaced at render time:
  /*__DATA__*/  -> JSON {nodes, edges, meta}
  __ROOT__ __FILES__ __EDGES__ __LOC__ -> summary stats
"""

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Vantage · Codebase Knowledge Graph</title>
<script src="https://unpkg.com/vis-network@9.1.9/standalone/umd/vis-network.min.js"></script>
<style>
  :root{
    --bg:#0b1020; --panel:#121a30; --panel2:#0f1626; --text:#e6edf7;
    --muted:#8aa0c2; --accent:#6366f1; --accent2:#06b6d4;
  }
  *{box-sizing:border-box}
  html,body{margin:0;height:100%;background:var(--bg);color:var(--text);
    font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Inter,sans-serif}
  header{display:flex;align-items:center;gap:18px;padding:14px 20px;
    background:linear-gradient(90deg,#121a30,#0d1426);border-bottom:1px solid #1e2a47}
  .brand{font-weight:800;font-size:20px;letter-spacing:.5px;
    background:linear-gradient(90deg,var(--accent),var(--accent2));
    -webkit-background-clip:text;background-clip:text;color:transparent}
  .stat{display:flex;flex-direction:column;line-height:1.1}
  .stat b{font-size:16px}.stat span{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.6px}
  .spacer{flex:1}
  #search{background:var(--panel2);border:1px solid #243150;color:var(--text);
    padding:9px 12px;border-radius:10px;width:280px;outline:none}
  #search:focus{border-color:var(--accent)}
  main{display:flex;height:calc(100% - 64px)}
  #graph{flex:1;height:100%}
  aside{width:300px;background:var(--panel);border-left:1px solid #1e2a47;
    padding:16px;overflow:auto}
  aside h3{margin:0 0 8px;font-size:13px;text-transform:uppercase;color:var(--muted);letter-spacing:.6px}
  #info{font-size:13px;white-space:pre-wrap;color:#cdd9ee;min-height:60px}
  .legend{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}
  .chip{display:flex;align-items:center;gap:6px;font-size:12px;color:var(--muted)}
  .dot{width:10px;height:10px;border-radius:50%}
  .hint{font-size:12px;color:var(--muted);margin-top:14px;line-height:1.5}
  kbd{background:#1c2742;border:1px solid #2c3a5e;border-radius:5px;padding:1px 6px;font-size:11px}
</style>
</head>
<body>
<header>
  <div class="brand">⛰ VANTAGE</div>
  <div class="stat"><b>__ROOT__</b><span>repository</span></div>
  <div class="stat"><b>__FILES__</b><span>files mapped</span></div>
  <div class="stat"><b>__EDGES__</b><span>dependencies</span></div>
  <div class="stat"><b>__LOC__</b><span>lines of code</span></div>
  <div class="spacer"></div>
  <input id="search" placeholder="🔎 filter files / modules…" />
</header>
<main>
  <div id="graph"></div>
  <aside>
    <h3>Inspector</h3>
    <div id="info">Click a node to inspect. Drag to pan, scroll to zoom.</div>
    <h3 style="margin-top:18px">Legend</h3>
    <div class="legend" id="legend"></div>
    <div class="hint">
      <b>Generated by Vantage</b> — the offline-first command center for your codebase.<br><br>
      • Diamonds are external dependencies.<br>
      • Arrows show import direction.<br>
      • Dashed edges = unresolved / third-party.
    </div>
  </aside>
</main>
<script>
const DATA = /*__DATA__*/;
const palette = DATA.meta.groups || {};
const ext = DATA.meta.ext_color || "#64748b";

const nodes = new vis.DataSet(DATA.nodes.map(n=>{
  const isExt = n.group === "ext";
  const color = isExt ? ext : (palette[n.group] || "#6366f1");
  return {
    id:n.id, label:n.label, title:n.title, group:n.group,
    shape: n.shape || "dot",
    size: n.size || 10,
    color:{ background:color, border: isExt? "#475569": color, highlight:{background:color,border:"#fff"} },
    font:{color:"#e6edf7", size:13},
    file: n.path || ""
  };
}));
const edges = new vis.DataSet(DATA.edges.map((e,i)=>({
  id:i, from:e.from, to:e.to, arrows:e.arrows, dashes:e.dashes,
  color:{color:(e.color&&e.color.opacity!=null)? "rgba(120,150,200,"+e.color.opacity+")":"#3a4a6b", opacity:.4},
  smooth:{type:"continuous"}
})));

const container = document.getElementById("graph");
const net = new vis.Network(container, {nodes,edges}, {
  physics:{ stabilization:true, barnesHut:{ gravitationalConstant:-8000, springLength:140, springConstant:0.04 } },
  interaction:{ hover:true, tooltipDelay:120, navigationButtons:false, keyboard:true },
  nodes:{ borderWidth:2 },
  edges:{ width:1 }
});

document.getElementById("legend").innerHTML = Object.entries(palette).map(([k,v])=>
  `<div class="chip"><span class="dot" style="background:${v}"></span>${k}</div>`).join("")
  + `<div class="chip"><span class="dot" style="background:${ext}"></span>external</div>`;

const info = document.getElementById("info");
net.on("click", params=>{
  if(params.nodes.length){
    const n = nodes.get(params.nodes[0]);
    info.textContent = n.title || n.label;
  } else if(params.edges.length){
    const e = edges.get(params.edges[0]);
    info.textContent = "Dependency edge";
  } else { info.textContent = "Click a node to inspect."; }
});

const search = document.getElementById("search");
search.addEventListener("input", ()=>{
  const q = search.value.toLowerCase();
  nodes.forEach(n=>{
    const hide = q && !(n.label.toLowerCase().includes(q) || (n.file||"").toLowerCase().includes(q));
    nodes.update({id:n.id, hidden:hide});
  });
  edges.forEach(e=>{
    const s=nodes.get(e.from), t=nodes.get(e.to);
    edges.update({id:e.id, hidden: (s.hidden||t.hidden)});
  });
  net.redraw();
});
</script>
</body>
</html>
"""
